name: Automatic Checkpoint

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * *"
    - cron: "30 22 * * *"

jobs:
  Checkpoint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install urllib3==1.25.11
          pip install requests

      - name: Checkpoint Save
        shell: bash
        run: python checkpoint.py
